---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: dex
  namespace: flux-system
spec:
  image: https://charts.dexidp.io
  interval: 5m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://charts.dexidp.io
