---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo-deploy-manual
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo-deploy-manual
  policy:
    semver:
      range: 5.0.x
