apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-deploy-manual
  namespace: default
spec:
  selector:
    matchLabels:
      app: podinfo-deploy-manual
  template:
    metadata:
      labels:
        app: podinfo-deploy-manual
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:5.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
