---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: dex
  namespace: flux-system
spec:
  image: charts.dexidp.io
  interval: 1m0s

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dex
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.dexidp.io
