apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: truecharts
  namespace: flux-system
spec:
  # url: https://truecharts.org/charts/stable/
  # url: oci://tccr.io/truecharts
  url: https://github.com/truecharts/charts/tree/master/charts/stable/sftpgo
  interval: 10m
